### ISSUE TITLE
Crease not operating as per physical module

### ISSUE THREAD

**Issue by ClintFrancis** [AlliewayAudio/AlliewayAudio_Freebies#2]
Hi there,

The crease output isn't working as per the hardware Cold Mac module.
Regardless of what goes in, the crease output never deviates (on a Mac)

**Comment by AlliewayAudio** [comment]
Hey, sorry I missed this comment - could you clarify what you mean by "deviates"? All my tests have showed it working the same as on the physical module from what I can tell (I used the equation from the official Cold Mac technical guide)

And it also may be worth testing this again using the most recent version for VCV V2, as there have been several code changes and it may have solved your issue perhaps.

Thanks for the report!
~Allie

**Comment by AlliewayAudio** [comment]
Closing this issue due to no response, will reopen if there is clarification on what the issue may be (if not already fixed).
