### ISSUE TITLE
V2 Compatibility

### ISSUE THREAD

**Issue by noodleboy91** [AlliewayAudio/AlliewayAudio_Freebies#3]
Are you going to make this compatible with V2 in the near future? Thank you

**Comment by AlliewayAudio** [comment]
Sorry for the delay! V2 coming very soon, I'm doing a larger update as well incorporating much feedback from trent of whimsical raps :) Stay tuned ^^

**Comment by AlliewayAudio** [comment]
Update has been posted, enjoy ^_^
~Allie

**Comment by noodleboy91** [comment]
thank you :)
